#EpicSMP: a bukkit/spigot plugin.
#I will explain what the different options are below in comments.

#DO NOT CHANGE THIS OPTION THE PLUGIN WILL BREAK.
config version: 1

#Messages used throughout the plugin.
plugin messages:
    #Prefix used before ALL messages.
    prefix: '&8[&bEpic&fSMP&8] &f'
    #No permission message.
    no permission: '&cSorry you don''t have permission.'

#Commands Section.   
commands:
    #Command /withdraw
    withdraw:
        #Permission for the command.
        permission: 'epicsmp.withdraw'
        #Use a number message.
        use a number: '&cPlease put a number.'
        #Too many or too little args message.
        too many or too little args: '&cToo Many or Too Little Args. Please only type one number after /withdraw. Eg: /withdraw 50'
        #Only players can use this command message.
        sender not player: '&4Only players can use this command.'
        
    #Command /epicsmp
    epicsmp:
        #Permission for the command.
        permission: 'epicsmp.epicsmp'
        #Help message.
        help: '&fPlease contact your server admin for help.'
        #License message.
        license: 'Find license info at: http://tinyurl.com/nqme93d'
        #If the player doesn't provide help or version after /epicsmp        
        not enough args: '&cPlease put "help" or "license" after /epicsmp.'
        
    #Command /buycommand    
    buycommand:
        #Permission for the command.
        permission: 'epicsmp.buycommand' 
        #If sender is not equal to player.
        not correct sender: '&cOnly players can use this command.'
        #Different Commands that can be bought.
        commands:
            one:
                #Name of the item.
                name: '&b/tpa'
                #Price of command (One Time Purchase)
                price: 2000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tpa                
            two:
                #Name of the item.
                name: '&b/tp'
                #Price of command (One Time Purchase)
                price: 3500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tp
                 - essentials.tp.others
                 - essentials.teleport.position
                 - essentials.tppos
            three:
                #Name of the item.
                name: '&b/tpahere'
                #Price of command (One Time Purchase)
                price: 2100
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tpahere  
            four:
                #Name of the item.
                name: '&b/tpall'
                #Price of command (One Time Purchase)
                price: 4500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tpall  
            five:
                #Name of the item.
                name: '&b/msg'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'BOOK'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.msg 
            six:
                #Name of the item.
                name: '&b/fix'
                #Price of command (One Time Purchase)
                price: 7500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ANVIL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.repair
                 - essentials.repair.all
                 - essentials.repair.armor
                 - essentials.repair.enchanted
            seven:
                #Name of the item.
                name: '&b/back'
                #Price of command (One Time Purchase)
                price: 7000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'BARRIER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.back
                 - essentials.back.ondeath
            eight:
                #Name of the item.
                name: '&b/broadcast'
                #Price of command (One Time Purchase)
                price: 1500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'COMMAND_MINECART'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.broadcast     
            nine:
                #Name of the item.
                name: '&b/clearinventory'
                #Price of command (One Time Purchase)
                price: 1500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'LAVA_BUCKET'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.clearinventory  
            ten:
                #Name of the item.
                name: '&b/craft'
                #Price of command (One Time Purchase)
                price: 5000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'WORKBENCH'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.workbench     
            eleven:
                #Name of the item.
                name: '&b/time'
                #Price of command (One Time Purchase)
                price: 6000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'WATCH'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.time
                 - essentials.time.set
            twelve:
                #Name of the item.
                name: '&b/feed'
                #Price of command (One Time Purchase)
                price: 7500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'COOKED_BEEF'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.feed     
            thirteen:
                #Name of the item.
                name: '&b/enderchest'
                #Price of command (One Time Purchase)
                price: 2000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_CHEST'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.enderchest
            fourteen:
                #Name of the item.
                name: '&b/fly'
                #Price of command (One Time Purchase)
                price: 8000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'FEATHER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.fly     
            fifteen:
                #Name of the item.
                name: '&b/hat'
                #Price of command (One Time Purchase)
                price: 2000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'GLASS'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.hat                     
            sixteen:
                #Name of the item.
                name: '&b/invsee'
                #Price of command (One Time Purchase)
                price: 4000
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'CHEST'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.invsee  
            seventeen:
                #Name of the item.
                name: '&b/heal'
                #Price of command (One Time Purchase)
                price: 6500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'GOLDEN_APPLE'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.heal                     
            eighteen:
                #Name of the item.
                name: '&b/lightning'
                #Price of command (One Time Purchase)
                price: 4500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'TORCH'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.lightning
            nineteen:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none
            twenty:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none
            twentyone:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none
            twentytwo:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none    
            twentythree:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none 
            twentyfour:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none 
            twentyfive:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none
            twentysix:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none
            twentyseven:
                #Name of the item.
                name: 'null'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'PAPER'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - none                    