#EpicSMP: a bukkit/spigot plugin.
#I will explain what the different options are below in comments.

#DO NOT CHANGE THIS OPTION THE PLUGIN WILL BREAK.
config version: 1

#Messages used throughout the plugin.
plugin messages:
    #Prefix used before ALL messages.
    prefix: '&8[&bEpic&fSMP&8] &f'
    #No permission message.
    no permission: '&cSorry you don''t have permission.'

#Commands Section.   
commands:
    #Command /epicsmp
    epicsmp:
        #Permission for the command.
        permission: 'epicsmp.epicsmp'
        #Help message.
        help: '&fPlease contact your server admin for help.'
        #License message.
        license: 'Find license info at: http://tinyurl.com/nqme93d'
        #If the player doesn't provide help or version after /epicsmp        
        not enough args: '&cPlease put "help" or "license" after /epicsmp.'
        
    #Command /buycommand    
    buycommand:
        #Permission for the command.
        permission: 'epicsmp.buycommand' 
        #If sender is not equal to player.
        not correct sender: '&cOnly players can use this command.'
        #Different Commands that can be bought.
        commands:
            one:
                #Name of the item.
                name: '&b/tpa'
                #Price of command (One Time Purchase)
                price: 500
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tpa                
            two:
                #Name of the item.
                name: '&b/tp'
                #Price of command (One Time Purchase)
                price: 600
                #Material of item. (MUST be a valid Bukkit Material. If it it not a valid Material it will default to PAPER)
                material: 'ENDER_PEARL'
                # A List of permissions that will be added when the item is bought.
                permissions:
                 - essentials.tp
                 - essentials.tp.others
                 - essentials.teleport.position
                 - essentials.tppos